-- Enable Row Level Security
alter table if exists public.users enable row level security;
alter table if exists public.locations enable row level security;
alter table if exists public.stations enable row level security;
alter table if exists public.announcements enable row level security;
alter table if exists public.station_status enable row level security;
alter table if exists public.submissions enable row level security;

-- USERS Table
create table if not exists public.users (
  id uuid references auth.users not null primary key,
  email text,
  role text default 'public',
  created_at timestamptz default now()
);

-- LOCATIONS Table
create table if not exists public.locations (
  id bigint generated by default as identity primary key,
  slug text unique,
  title text,
  poster_url text,
  story text,
  youtube_url text,
  display_order int,
  is_published boolean default true,
  updated_by uuid references public.users,
  updated_at timestamptz default now()
);

-- STATIONS Table
create table if not exists public.stations (
  id bigint generated by default as identity primary key,
  slug text unique,
  title text,
  poster_url text,
  description text,
  youtube_url text,
  display_order int,
  is_published boolean default true,
  updated_by uuid references public.users,
  updated_at timestamptz default now()
);

-- ANNOUNCEMENTS Table
create table if not exists public.announcements (
  id bigint generated by default as identity primary key,
  title text,
  body text,
  starts_at timestamptz,
  ends_at timestamptz,
  is_published boolean default false,
  updated_by uuid references public.users,
  updated_at timestamptz default now()
);

-- STATION STATUS Table
create table if not exists public.station_status (
  id bigint generated by default as identity primary key,
  station_id bigint references public.stations,
  status text,
  note text,
  updated_by uuid references public.users,
  updated_at timestamptz default now()
);

-- SUBMISSIONS Table
create table if not exists public.submissions (
  id bigint generated by default as identity primary key,
  submitted_by uuid references auth.users,
  target_type text,
  target_id text,
  title text,
  content_type text,
  payload jsonb,
  notes text,
  status text default 'pending',
  reviewed_by uuid references public.users,
  reviewed_at timestamptz,
  created_at timestamptz default now()
);

-- RLS POLICIES

-- Public Policies (Read Only)
create policy "Public read published locations"
  on public.locations for select
  using ( is_published = true );

create policy "Public read published stations"
  on public.stations for select
  using ( is_published = true );

create policy "Public read published announcements"
  on public.announcements for select
  using (
    is_published = true
    and (starts_at is null or starts_at <= now())
    and (ends_at is null or ends_at >= now())
  );

-- Admin Policies (Full Access to everything)
create policy "Admins have full access to locations"
  on public.locations for all
  using ( exists ( select 1 from public.users where id = auth.uid() and role = 'admin' ) );

create policy "Admins have full access to stations"
  on public.stations for all
  using ( exists ( select 1 from public.users where id = auth.uid() and role = 'admin' ) );

create policy "Admins have full access to announcements"
  on public.announcements for all
  using ( exists ( select 1 from public.users where id = auth.uid() and role = 'admin' ) );

create policy "Admins have full access to station_status"
  on public.station_status for all
  using ( exists ( select 1 from public.users where id = auth.uid() and role = 'admin' ) );

create policy "Admins have full access to submissions"
  on public.submissions for all
  using ( exists ( select 1 from public.users where id = auth.uid() and role = 'admin' ) );
  
create policy "Admins have full access to users"
  on public.users for all
  using ( exists ( select 1 from public.users where id = auth.uid() and role = 'admin' ) );


-- Volunteer Policies
create policy "Volunteers read all locations"
  on public.locations for select
  using ( exists ( select 1 from public.users where id = auth.uid() and role in ('volunteer', 'admin') ) );

create policy "Volunteers read all stations"
  on public.stations for select
  using ( exists ( select 1 from public.users where id = auth.uid() and role in ('volunteer', 'admin') ) );

create policy "Volunteers create submissions"
  on public.submissions for insert
  with check ( exists ( select 1 from public.users where id = auth.uid() and role in ('volunteer', 'admin') ) );

-- Self Policies
create policy "Users can read own data"
  on public.users for select
  using ( auth.uid() = id );
  
-- Triggers
-- Handle new user signup -> insert into public.users
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.users (id, email, role)
  values (new.id, new.email, 'public');
  return new;
end;
$$ language plpgsql security definer;

create or replace trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();
